# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lengthTabu', models.IntegerField()),
                ('iterationsWithoutImprovement', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('algorithm', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='file',
            name='date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AlterField(
            model_name='file',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Student'),
        ),
        migrations.AddField(
            model_name='file',
            name='Task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Task'),
        ),
    ]
