# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20190611_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='result_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_file', to='tests.File'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
