# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20190604_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='nameOfFile',
            new_name='name_of_file',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='value',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='date_of_starting',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='iterationsWithoutImprovement',
            new_name='iterations_without_improvement',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='lengthTabu',
            new_name='progress',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='type_of_algorithm',
        ),
        migrations.AddField(
            model_name='task',
            name='tabu_length',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
