# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20190605_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name_of_file',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date_of_starting',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Student',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='file',
            name='Task',
        ),
        migrations.RemoveField(
            model_name='file',
            name='score',
        ),
        migrations.RemoveField(
            model_name='task',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type_of_algorithm',
        ),
        migrations.AddField(
            model_name='task',
            name='iterations',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='matrix_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.File'),
        ),
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
