# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20190605_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='iterations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='iterations_without_improvement',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tabu_length',
            field=models.IntegerField(null=True),
        ),
    ]
